### ISSUE TITLE
À faire : rendu du code

### ISSUE THREAD

**Issue by matteodelabre** [matteodelabre/projet-cmi#2]
## Jeu

- [x] Rotation de la caméra en changeant la gravité
- [x] Changement des contrôles selon la gravité
- [x] État pause
- [x] État mort
- [x] État gagné
- [x] Calcul de l'état mort, tue les entités en dehors des bords

## Blocs spéciaux

- [x] Arrivée
- [x] Mort
- [x] Déplaçable
- [x] Change polarité

## Éditeur

- [x] Scroll par molette (shift + molette aussi)
- [x] Polarisation de blocs
- [x] Sauvegarde
- [x] Sélecteur de bloc
- [x] Affichage et modification zone de jeu

## Général

- [x] Renommer PHYSICS_TIME et uniformiser les FPS
- [x] Vérifier toute fuite mémoire
- [x] Virer les pointeurs inutiles
- [x] Séparation ID collision ID type
- [x] Renommer View => State
- [x] Choix des textures des blocs
- [x] Décider entre smooth ou pas smooth
- [x] Caméra qui tremble
- [x] ~~Limiter la taille de la fenêtre~~ **impossible avec la SFML**

## Bugs

- [x] Bug : "ne répond pas" alors qu'il répond
- [x] Image du menu pas a la bonne taille
- [x] Sélectionner un bloc au démarrage de l'éditeur, sinon il plante
- [x] Adaptation de la taille de la fenêtre a la sortie du menu ou encore lors du test dans l'éditeur
- [x] Résoudre les comportement étrange des contrôle et de la caméra quand le nombre de joueurs est supérieur a 2.
- [x] la supretion ne supprime pas tous les blocs selectionné dans l'éditeur
- [x] imposible de joué au niveau tuto, pas de controle des balle car grisse.
- [x] la caméra suis les balle en trop. sugestion : empéché de mettre plus de 3 balles.
- [x] les caise peuvent fair planter le jeu

**Comment by MaelleB** [comment]
-[] Colorisation des images 
-[] Finir la page de règles
-[] Mettre en place la page de règles

**Comment by remiceres** [comment]
- [ ] finir les texture en SVG
- [ ] terminer texture blocs
- [ ] création des niveaux

**Comment by MaelleB** [comment]
Bugs : 
- [ ] affichage en miniature du fond du menu à l'ouverture du jeu

**Comment by remiceres** [comment]
## choses éventuelle a faire.
- [ ]  faire un fonction exporté différent de sauvegardé. Cela permet de placer le niveau dans la des niveaux.
- [ ] pour les zone de texte faire le pus basique possible, elle ne prend en compte que la touche retour. Pas la peine de s’embête avec les fléché , le ctrl+A ect.
- [ ] scrolling dans le menu des niveau ( je pense que c'est trop lourd a faire et ce n'est pas un priorité)
- [ ] menu pause , mort , victoire
- [ ] terminer l'editeur
